language: rust
sudo: false

cache: cargo
cache:
    directories:
      - $HOME/.cargo
      - $HOME/target

rust:
  - beta
  - nightly

matrix:
    allow_failures:
      - rust: nightly
    fast_finish: true
    include:
      - os: linux
        rust: stable
        compiler: gcc

      - os: windows
        rust: stable

      - os: osx
        rust: stable

script:
  - cargo update
  - cargo test --all --features="journal, user, clock, files" # --all-features # TODO

notifications:
  email: false
  webhooks:
    urls:
      - https://cala.zulipchat.com/api/v1/external/travis?api_key=dCMe2lR9z6lOfH1ucaZagWphH6p4TumS&stream=travis-ci&topic=cala&ignore_pull_requests=false
    on_success: change
    on_failure: always
